name: Auto Compile and Release Code Template PDF

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install LaTeX environment
              run: |
                  sudo apt update && sudo apt install -y texlive-full latexmk

            - name: Install custom fonts
              run: |
                  mkdir -p ~/.fonts
                  find font -type f -name '*.ttf' -exec cp {} ~/.fonts/ \; || true
                  find font -type f -name '*.otf' -exec cp {} ~/.fonts/ \; || true
                  fc-cache -f -v

            - name: Compile note/code.tex
              run: |
                  if [ -d "note" ]; then
                    cd note
                    xelatex code.tex
                    xelatex code.tex
                    cd ..
                  else
                    echo "Note directory not found, skipping compilation"
                  fi

            - name: Prepare PDF for release
              run: |
                  mkdir -p release_pdf
                  [ -f "note/code.pdf" ] && cp note/code.pdf release_pdf/ || echo "Note PDF not found"

            - name: Delete existing release
              uses: dev-drprasad/delete-tag-and-release@v0.2.1
              with:
                  tag_name: latest
                  delete_release: true
                  repo: ${{ github.repository }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              continue-on-error: true

            - name: Create/Update release
              id: create_release
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: latest
                  name: Latest PDF
                  body: "ACM 板子"
                  files: |
                      release_pdf/code.pdf
                  draft: false
                  prerelease: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
